#!/bin/sh

# Startup
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-scale --randomize ~/Pictures/wallpapers/* &
udiskie -a &

# Scripts
~/.config/polybar/launch.sh --grayblocks

# Main Config
bspc config border_width         0
bspc config window_gap           8
bspc config split_ratio          0.5

for monitor in $(bspc query -M --names | tail -1); do
	bspc monitor $monitor -d 1 2 3 4 5
done

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
